[package]
name = "ultimate_red_team_malware"
version = "1.0.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["memoryapi", "processthreadsapi", "tlhelp32", "winnt", "handleapi", "debugapi"] }
aes = "0.8"
rand = "0.8"
ctr = "0.9"
